config/routes.rb
Macabakco::Application.routes.draw do
  
  root 'leagues#index'

  devise_for :admins

  get 'about', to: 'homes#about'
  get 'advertisement', to: 'homes#advertisement'
  get 'contact', to: 'homes#contact'
  resources :leagues, only: [:index] do           
      resources :matches, only: [:index]
  end  

  namespace :admin do
    get 'home', to: 'homes#home_action'
    get 'about', to: 'homes#about'
    get 'advertisement', to: 'homes#advertisement'
    get 'contact', to: 'homes#contact'
    get 'teamsbyleague', to: 'teams#teamsbyleague' #categorize teams by league
    resources :channels
    resources :leagues
    resources :teams
    resources :matches, only: [:destroy]
    resources :leagues  do
      resources :teams
      resources :matches do
        collection do
          get :bulk_edit
          put :bulk_update
        end 
      end
    end  
  end

  

  

end

app/models/league.rb
class League < ActiveRecord::Base
	has_many :assignments
	has_many :matches
	has_many :teams, through: :assignments
	validates_presence_of :name
  	validates_uniqueness_of :name
	
end

app/controllers/admin/leagues_controller.rb
class Admin::LeaguesController < ApplicationController

   before_action :set_league, only: [:show, :edit, :update, :destroy]	
   before_action :authenticate_admin!

   def index
		@leagues = League.all
   end

   def show
   		#Set league runs.
   end

   def new
    @league = League.new
  end

   def edit
   		#Set league runs.
   end

   def create
		@league = League.new(league_params)

		respond_to do |format|
	      if @league.save
	        format.html { redirect_to admin_league_path(@league), notice: 'League was successfully created.' }
	      else
	        format.html { render action: 'new', notice: "League coudnt created! :( #{@league.errors.full_messages.join(",")}" }
	      end
    	end
   end

   def update
   	#Set league runs.
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to admin_leagues_path, notice: 'League was successfully updated.' }
      else
        format.html { render action: 'edit', notice: "League coudnt updated! :( #{@league.errors.full_messages.join(",")}" }
      end
    end
  end

  def destroy
  	#Set league runs.
    @league.destroy
    respond_to do |format|
      format.html { redirect_to admin_leagues_path, notice: 'League was successfully deleted.' }
    end
  end



  private
  
  # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end	  
  # Never trust parameters from the scary internet, only allow the white list through.
  def league_params
      params.require(:league).permit(:id,:name, :flag)
  end
end 

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

  
  def index
    @leagues = League.all
  end


  end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_for(@league) do |f| %>
  <% if @league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @league.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leagues/edit.html.erb
<h1>Editing league</h1>

<%= render 'form' %>

<%= link_to 'Show', @league, class: 'admin-link' %> |
<%= link_to 'Back', leagues_path, class: 'admin-link' %>

app/views/leagues/index.html.erb
<div class="flags-content">  
  <% @leagues.each do |league| %>
    <%= div_for league do %>
      <%= link_to league_matches_path(league) do %>
      <%= image_tag "#{league.flag}.png" %>
      <% end %>
    <%end%>
  <% end %>
</div>
  
<div class="clearfix"></div>

app/views/leagues/new.html.erb
<h1>New league</h1>

<%= render 'form' %>

<%= link_to 'Back', leagues_path, class: 'admin-link' %>

app/views/leagues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @league.name %>
</p>

<%= link_to 'Edit', edit_league_path(@league), class: 'admin-link' %> |
<%= link_to 'Back', leagues_path, class: 'admin-link' %>