config/routes.rb
Macabakco::Application.routes.draw do
  
  root 'leagues#index'

  devise_for :admins

  get 'about', to: 'homes#about'
  get 'advertisement', to: 'homes#advertisement'
  get 'contact', to: 'homes#contact'
  resources :leagues, only: [:index] do           
      resources :matches, only: [:index]
  end  

  namespace :admin do
    get 'home', to: 'homes#home_action'
    get 'about', to: 'homes#about'
    get 'advertisement', to: 'homes#advertisement'
    get 'contact', to: 'homes#contact'
    get 'teamsbyleague', to: 'teams#teamsbyleague' #categorize teams by league
    resources :channels
    resources :leagues
    resources :teams
    resources :matches, only: [:destroy]
    resources :leagues  do
      resources :teams
      resources :matches do
        collection do
          get :bulk_edit
          put :bulk_update
        end 
      end
    end  
  end

  

  

end

app/models/match.rb
class Match < ActiveRecord::Base
	
	validates_uniqueness_of :home_id, scope: [:away_id, :league_id]
	validates_presence_of :date_time
	validates_with DifferentTeam


	belongs_to :league
	belongs_to :channel	
	belongs_to :away_team, class_name: "Team", foreign_key: :away_id
    belongs_to :home_team, class_name: "Team", foreign_key: :home_id


 end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < ApplicationController

	before_action :set_matches, only: [:index, :new, :create, :update, :bulk_edit, :bulk_update]
  before_action :authenticate_admin!
  	
  

	def index
	 #set_matches runs!
	end

  def new
    @match = Match.new
    @channels = Channel.all
    @teams = Team.all 
  end

  def create

    error = false
    @match = @league.matches.new(match_params)

    respond_to do |format|
        if !@match.save
          format.html { redirect_to new_admin_league_match_path(@league), notice: "Match coudnt created! :( #{@match.errors.full_messages.join(",")}"  }
        else
          format.html { redirect_to admin_league_matches_path(@match.league), notice: 'Matches was successfully created! :)' }
        end
    end

  end

  def bulk_edit
    #set_matches runs.
    @teams = @league.teams
    @channels = Channel.all
    @leagues = League.all 
  end




  def bulk_update
    error = false
    matches = params[:match]
    last_match = nil
    matches.each do |id, data|
      m = Match.find(id)
      m.home_id = data["home_team"]
      m.away_id = data["away_team"]
      m.channel_id = data["channel"]
      m.date_time = DateTime.parse(data["date_time"])
      if !m.save
        last_match = m
        error = true
        break
      end
    end

    respond_to do |format|
        if error
          format.html { redirect_to bulk_edit_admin_league_matches_path(@league), 
            notice: "Matches coudnt updated! Maybe home and away
             teams are the same in a match or you have tried 
             to save the same match two times! :( #{last_match.errors.full_messages.join(",")}" }
        else
          format.html { redirect_to admin_league_matches_path(@league), notice: 'Matches were successfully updated! :)' }
        end
      end
  end

  def destroy
    @match = Match.find(params[:id])
    @league = @match.league
    @match.destroy

    respond_to do |format|
      format.html { redirect_to admin_league_matches_path(@league), notice: 'Match was successfully deleted.' }
    end
  end

 #######################Private Methods###########################################
	private
  # Use callbacks to share common setup or constraints between actions.

  def set_matches
    @league = League.find(params[:league_id])
    @matches = @league.matches
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def match_params
    params.require(:match).permit(:home_id, :away_id, :channel_id, :date_time)
  end
 ################################################################################


end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

	before_action :set_matches, only: [:index]

	def index
		#set_matches runs.
	end

	private
  # Use callbacks to share common setup or constraints between actions.
  def set_matches
    @league = League.find(params[:league_id])
    @matches = @league.matches
  end

end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/admin/matches/_form.html.erb
<%= form_for :admin, url: admin_league_matches_path, method: :post do %> 

  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= fields_for :match, @match do |match_form| %>
    
   

    <div class="field">
      <%= match_form.label :home_id, "Home" %><br>
      <%= match_form.select(:home_id, options_from_collection_for_select(@teams, 'id', 'name',@match.home_id) ) %>
    </div>

    <div class="field">
      <%= match_form.label :away_id, "Away" %><br>
      <%= match_form.select(:away_id, options_from_collection_for_select(@teams, 'id', 'name',@match.away_id) ) %>
    </div>

    <div class="field">
      <%= match_form.label :channel_id, "Channel" %><br>
      <%= match_form.select(:channel_id, options_from_collection_for_select(@channels, 'id', 'name',@match.channel_id) ) %>
    </div>

    <div class="field">
      <%= match_form.label :date_time, "Date and Time" %><br>
      <%= match_form.text_field :date_time, value: @match.date_time, class: "datetimepicker" %>
    </div>
  
    <div class="actions">
      <%= match_form.submit %>
    </div>

  <%end%>

<% end %>

app/views/admin/matches/_form_editmbl.html.erb
<%= form_for :admin,  url: bulk_update_admin_league_matches_path, method: :put do %>
 
  <table class="edit-table">
 
    <tr>
      <th>Home</th>
      <th>Away</th>
      <th>Channel</th>
      <th>Date/Time</th>
      <th>Destroy</th>
    </tr>
        
      <% @matches.each do |match| %>
        <%= fields_for "match[]", match do |match_form| %>
          <tr>
            <td><%= match_form.select(:home_team, options_from_collection_for_select(@teams, 'id', 'name',match.home_id) ) %></td>
            <td><%= match_form.select(:away_team, options_from_collection_for_select(@teams, 'id', 'name',match.away_id) ) %></td>
            <td><%= match_form.select(:channel, options_from_collection_for_select(@channels, 'id', 'name',match.channel_id) ) %></td>
            <td><%= match_form.text_field :date_time, value: match.date_time.strftime("%Y/%m/%d %H:%M"), class: "datetimepicker" %></td>
            <td><%= link_to 'Destroy', admin_match_path(match), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% end %>
 
  </table>
 
  <%= submit_tag 'Update' %>
<% end %>

app/views/admin/matches/bulk_edit.html.erb
<h1>Editing Matches</h1>

<%= render 'form_editmbl' %>

<%= link_to 'Back', admin_league_matches_path, class: 'admin-link'%>
<%= link_to ' | Add New Match', new_admin_league_match_path(@league), class: 'admin-link' %>

app/views/admin/matches/index.html.erb
<div id="genel_sayfa">
  <h1><%= @league.name.titleize%></h1>
  <table class="mactablosu">
    
    <thead></thead>

    <tbody>
      <% @matches.each do |match| %>
        <tr>
          <td>
            <p class="mac"><%= match.home_team.name %> - <%= match.away_team.name %></p>
            <p><%= match.date_time.strftime("%d %B %A %H:%M")%> 
            <span style="color:#1EB300"><%= match.channel.name %></span></p>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Back |', admin_home_path, class: 'admin-link' %>
<%= link_to bulk_edit_admin_league_matches_path(@league), class: 'admin-link' do %>
  Edit matches of <%= @league.name%>
<%end%>


app/views/admin/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_home_path, class: 'admin-link'%>