config/routes.rb
Macabakco::Application.routes.draw do
  
  root 'leagues#index'

  devise_for :admins

  get 'about', to: 'homes#about'
  get 'advertisement', to: 'homes#advertisement'
  get 'contact', to: 'homes#contact'
  resources :leagues, only: [:index] do           
      resources :matches, only: [:index]
  end  

  namespace :admin do
    get 'home', to: 'homes#home_action'
    get 'about', to: 'homes#about'
    get 'advertisement', to: 'homes#advertisement'
    get 'contact', to: 'homes#contact'
    get 'teamsbyleague', to: 'teams#teamsbyleague' #categorize teams by league
    resources :channels
    resources :leagues
    resources :teams
    resources :matches, only: [:destroy]
    resources :leagues  do
      resources :teams
      resources :matches do
        collection do
          get :bulk_edit
          put :bulk_update
        end 
      end
    end  
  end

  

  

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

	before_action :authenticate_admin!

	def home_action
    @leagues = League.all
  	end

  	

  	def about

  	end

  	

  	def advertisement

  	end

  	

  	def contact

  	end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController


  	def about

  	end

  	
  	def advertisement

  	end

  	

  	def contact

  	end

end

app/views/admin/homes/about.html.erb
<div id="genel_sayfa">
	<h1>Hakkımızda</h1>
		
	<p class="site">macabak!co - Futbolun yayın akışına ışık tutar. <br><br>
	
	Televizyon kanalları üzerinden izleyebileceğiniz maçların yayın akışını
	kolayca takip etmenizi sağlar. Amacımız hangi maç ne zaman hangi kanalda sorusuna cevap vermektir. Olur da
	maç saatini falan yanlış girersek bize kızmayın. Futbolda var bunlar.</p>
	
	<p class="site">macabak.co web sitemiz, sitemizde gözüken facebook sayfamız, twitter hesabımız ve
	youtube kanalımız dışında başka hiçbir site ya da bağlantıyla ilişkimiz yoktur.</p>
	
	<p class="site">macabak.co &copy;2014- Tüm hakları saklıdır.</p>
	
	<p class="site">Bu hizmeti beğendiyseniz geliştirilmesine katkıda bulunabilirsiniz.</p>
	
	<form id="bagis" action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
		<input type="hidden" name="cmd" value="_s-xclick">
		<input type="hidden" name="hosted_button_id" value="BBSTFUP7LRL7J">
		<input type="image" src="https://www.paypalobjects.com/tr_TR/TR/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - Online ödeme yapmanın daha güvenli ve kolay yolu!">
		<img alt="" border="0" src="https://www.paypalobjects.com/tr_TR/i/scr/pixel.gif" width="1" height="1">
	</form>
</div>

app/views/admin/homes/advertisement.html.erb
<div id="genel_sayfa">
	<h1>Reklam</h1>
	<p class="site">macabak!co'nun futbol sever kitlesine ulaşmak için buradan buyrun lütfen. reklam@macabak.co</p>
</div>

app/views/admin/homes/contact.html.erb
<div id="genel_sayfa">
				<h1>İletişim</h1>
				<p class="site">Öneri, istek ve şikayetlerinizi info@macabak.co adresimize gönderebilirsiniz.</p>
			</div>

app/views/admin/homes/home_action.html.erb
<div class="flags-content">  
  <% @leagues.each do |league| %>
    <%= div_for league do%>
      <%= link_to admin_league_matches_path(league) do %>
      <%= image_tag "#{league.flag}.png" %>
      <% end %>
    <%end%>
  <% end %>
</div>

<div id="admin-link-panel">
	<%= link_to 'Log Out |', destroy_admin_session_path, method: :delete, class: 'admin-link' %>
	<%= link_to 'Manage Channels |', admin_channels_path, class: 'admin-link' %>
	<%= link_to 'Manage Teams |', admin_teamsbyleague_path, class: 'admin-link' %>
	<%= link_to 'Manage Leagues', admin_leagues_path, class: 'admin-link' %>
</div>