config/routes.rb
Macabakco::Application.routes.draw do
  
  root 'leagues#index'

  devise_for :admins

  get 'about', to: 'homes#about'
  get 'advertisement', to: 'homes#advertisement'
  get 'contact', to: 'homes#contact'
  resources :leagues, only: [:index] do           
      resources :matches, only: [:index]
  end  

  namespace :admin do
    get 'home', to: 'homes#home_action'
    get 'about', to: 'homes#about'
    get 'advertisement', to: 'homes#advertisement'
    get 'contact', to: 'homes#contact'
    get 'teamsbyleague', to: 'teams#teamsbyleague' #categorize teams by league
    resources :channels
    resources :leagues
    resources :teams
    resources :matches, only: [:destroy]
    resources :leagues  do
      resources :teams
      resources :matches do
        collection do
          get :bulk_edit
          put :bulk_update
        end 
      end
    end  
  end

  

  

end

app/models/team.rb
class Team < ActiveRecord::Base
	has_many :assignments
	has_many :leagues, through: :assignments
	has_many :home_matches, class_name: "Match", foreign_key: :home_id, dependent: :destroy
  	has_many :away_matches, class_name: "Match", foreign_key: :away_id, dependent: :destroy
  	validates_presence_of :leagues
  	validates_presence_of :name
  	validates_uniqueness_of :name
end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < ApplicationController

   before_action :set_team, only: [:show, :destroy]	
   before_action :authenticate_admin!


   def index
    @league = League.find(params[:league_id])
    @@deneme = @league.id
    @teams = @league.teams
   end

   def show
   		#set_team runs.
   end

   def teamsbyleague
    @leagues = League.all
   end

   def new
    @leagues = League.all
    @team = Team.new
   end


   def create
    @leagues = League.all
		@team = Team.new(team_params.except(:leagues))

    team_params[:leagues].each do |league| 
    @team.leagues << League.find(league) if league != ""
    end

		respond_to do |format|
	      if @team.save
	        format.html { redirect_to admin_teamsbyleague_path, notice: 'Team was successfully created.' }
	      else
	        format.html { render action: 'new', notice: '#{@team.errors.full_messages.join(",")}' }
	      end
    	end
   end



  def destroy
  	#Set team runs.
    @team.destroy
    respond_to do |format|
      format.html { redirect_to admin_teamsbyleague_path, notice: 'Team was successfully deleted.' }
    end
  end



  private
  
  # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end	  
  # Never trust parameters from the scary internet, only allow the white list through.
  def team_params
      params.require(:team).permit(:id, :name, leagues:[])
  end
end 

app/views/admin/teams/_form.html.erb
<%= form_for [:admin, @team] do |f| %>

  <% if @team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@team.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @team.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.collection_check_boxes :leagues, @leagues, :id, :name, {}, {} do |b| %>
      <div class="checkboxes">
        <%= b.check_box %>
        <%= b.label %>
      </div>
    <%end%>
  </div><br>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/admin/teams/edit.html.erb
<h1>Editing team</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_team_path(@team), class: 'admin-link' %> |
<%= link_to 'Back', admin_team_path, class: 'admin-link' %>

app/views/admin/teams/index.html.erb
<h1>Listing teams</h1>

<table class="table-bg">
  <thead>
    <tr>
      <th>Name</th>
      <th>Show</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @teams.each do |team| %>
      <tr>
        <td><%= team.name %></td>
        <td><%= link_to 'Show', admin_team_path(team) %></td>
        <td><%= link_to 'Destroy', admin_team_path(team), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back |', admin_teamsbyleague_path, class: 'admin-link' %>
<%= link_to 'New Team', new_admin_team_path, class: 'admin-link' %>

app/views/admin/teams/new.html.erb
<h1>New Team</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_teamsbyleague_path, class: 'admin-link' %>

app/views/admin/teams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @team.name %>
</p>



<%= link_to 'Back', admin_home_path, class: 'admin-link' %>

app/views/admin/teams/teamsbyleague.html.erb
<h1>Manage Teams</h1>


<div class="flags-content">  
  <% @leagues.each do |league| %>
	    <%= div_for league do %>
	      <%= link_to admin_league_teams_path(league) do %>
	      		<%= image_tag "#{league.flag}.png" %>
	      <% end %>
	    <%end%>
  <% end %>
</div>

<div class="clearfix"></div>

<div id="admin-link-panel">
	<%= link_to "Back", admin_home_path, class: "admin-link" %>
</div>